creat readme file
GSG-CF05/Delivery-Team-6 pull request #4
Opened 2022-02-07 09:28 UTC by Hanahosam

2022-02-07 09:32 UTC, MzSalout approved these changes

2022-02-07 09:47 UTC, htahrawi approved these changes, later dismissed

2022-02-07 12:58 UTC, MzSalout requested changes
the images in readme file are not shown

2022-02-07 21:13 UTC, MzSalout approved these changes, later dismissed

2022-02-09 16:01 UTC, Yousef-Dall approved these changes

2022-02-09 16:05 UTC, merged